/**
 * Vocabulario de acciones de la auditoria operativa (AuditLog.action).
 *
 * docs/04 1299-1311 da ejemplos (`PRODUCT_PRICE_CHANGED`, ...) pero no fija un
 * catalogo cerrado. Se declara como constante para no usar strings libres y
 * para que el futuro `GET /audit` pueda filtrar por accion.
 *
 * docs/05 1814-1835 / RF-140: como minimo deben auditarse el cambio de precio,
 * el cambio de costo (fuera de esta fase, D4) y las activaciones/desactivaciones
 * relevantes.
 */
export const AUDIT_ACTIONS = {
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_ACTIVATED: 'PRODUCT_ACTIVATED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  PRODUCT_PRICE_CHANGED: 'PRODUCT_PRICE_CHANGED',
  PRESENTATION_CREATED: 'PRESENTATION_CREATED',
  PRESENTATION_UPDATED: 'PRESENTATION_UPDATED',
  PRESENTATION_DEFAULT_CHANGED: 'PRESENTATION_DEFAULT_CHANGED',
  PRESENTATION_ACTIVATED: 'PRESENTATION_ACTIVATED',
  PRESENTATION_DEACTIVATED: 'PRESENTATION_DEACTIVATED',
  CATALOG_ITEM_CREATED: 'CATALOG_ITEM_CREATED',
  CATALOG_ITEM_UPDATED: 'CATALOG_ITEM_UPDATED',
  CATALOG_ITEM_ACTIVATED: 'CATALOG_ITEM_ACTIVATED',
  CATALOG_ITEM_DEACTIVATED: 'CATALOG_ITEM_DEACTIVATED',
  // Fase 5 — inventario (docs/04 1299-1311, docs/05 1814-1835 / RF-140).
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
  PRODUCT_COST_CHANGED: 'PRODUCT_COST_CHANGED',
  // Fase 6 — proveedores y compras (docs/05 1834-1855 / RF-140: "compra cancelada").
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  SUPPLIER_ACTIVATED: 'SUPPLIER_ACTIVATED',
  SUPPLIER_DEACTIVATED: 'SUPPLIER_DEACTIVATED',
  PURCHASE_CREATED: 'PURCHASE_CREATED',
  PURCHASE_UPDATED: 'PURCHASE_UPDATED',
  PURCHASE_COMPLETED: 'PURCHASE_COMPLETED',
  PURCHASE_CANCELLED: 'PURCHASE_CANCELLED',
  // Fase 7 — clientes y ventas. RF-140 / RP-022 / docs/04 1302-1303 exigen
  // auditar como minimo la cancelacion de venta (`SALE_CANCELLED`). El resto se
  // audita por consistencia con Productos y Compras (docs/04 seccion 47 D13).
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_ACTIVATED: 'CUSTOMER_ACTIVATED',
  CUSTOMER_DEACTIVATED: 'CUSTOMER_DEACTIVATED',
  CUSTOMER_CREDIT_LIMIT_CHANGED: 'CUSTOMER_CREDIT_LIMIT_CHANGED',
  SALE_CREATED: 'SALE_CREATED',
  SALE_UPDATED: 'SALE_UPDATED',
  SALE_COMPLETED: 'SALE_COMPLETED',
  SALE_CANCELLED: 'SALE_CANCELLED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
